#language
language: java

#jdk version
jdk:
  - oraclejdk8

script:
  - ant build
  - ant AllTests
  - ant junitreport
  - ant clean

#notifications
#notifications:
 # email: false
 # slack: 321-group-5:TREpBvfUTMyUP9OtVm84Qwu1
